# Generated by Django 5.2.9 on 2025-12-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Durak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durak_no', models.CharField(max_length=50, unique=True, verbose_name='Durak Numarası')),
                ('durak_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Durak Adı')),
                ('enlem', models.FloatField(blank=True, null=True)),
                ('boylam', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_hat_no', models.IntegerField(verbose_name='Ana Hat No')),
                ('alt_hat_no', models.IntegerField(verbose_name='Alt Hat No')),
                ('ana_hat_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ana Hat Adı')),
                ('alt_hat_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Hat Adı')),
                ('durak_sayisi', models.IntegerField(blank=True, default=0, null=True)),
                ('uzunluk_km', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name': 'Hat',
                'verbose_name_plural': 'Hatlar',
                'unique_together': {('ana_hat_no', 'alt_hat_no')},
            },
        ),
        migrations.CreateModel(
            name='DurakVaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikis_zaman', models.DateTimeField(blank=True, null=True)),
                ('varis_zaman', models.DateTimeField(blank=True, null=True)),
                ('arac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('baslangic_durak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kalkis_yapanlar', to='api.durak')),
                ('bitis_durak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varis_yapanlar', to='api.durak')),
                ('hat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hat')),
            ],
        ),
        migrations.CreateModel(
            name='HatDurak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(verbose_name='Sıra No')),
                ('istikamet', models.CharField(blank=True, max_length=255, null=True)),
                ('durak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatlar', to='api.durak')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duraklar', to='api.hat')),
            ],
            options={
                'ordering': ['hat', 'sira'],
                'unique_together': {('hat', 'durak', 'sira')},
            },
        ),
        migrations.CreateModel(
            name='TalepVerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih_saat', models.DateTimeField()),
                ('yolcu_sayisi', models.IntegerField(default=1)),
                ('durak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.durak')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hat')),
            ],
            options={
                'indexes': [models.Index(fields=['hat', 'tarih_saat'], name='api_talepve_hat_id_ab8ba5_idx')],
            },
        ),
    ]
