# Generated by Django 5.2.9 on 2025-12-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='durakvaris',
            name='gecen_sure_saniye',
            field=models.IntegerField(default=0, help_text='Saniye cinsinden süre'),
        ),
    ]
