# Generated by Django 5.2.9 on 2025-12-16 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_durakvaris_gecen_sure_saniye'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatGuzergah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField()),
                ('enlem', models.FloatField()),
                ('boylam', models.FloatField()),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guzergah_noktalari', to='api.hat')),
            ],
            options={
                'ordering': ['hat', 'sira'],
                'unique_together': {('hat', 'sira')},
            },
        ),
    ]
