# Generated by Django 5.2.9 on 2025-12-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hatguzergah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durakvaris',
            name='gecen_sure_saniye',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HatTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(blank=True, max_length=50)),
                ('kalkis_saati', models.TimeField()),
                ('tarife_tipi', models.CharField(default='Hafta İçi', max_length=50)),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifeler', to='api.hat')),
            ],
        ),
    ]
