# Generated by Django 5.2.9 on 2025-12-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_durakvaris_gecen_sure_saniye_hattarife'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkSefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalkis_saati', models.TimeField(verbose_name='Ek Sefer Saati')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Sefer Tarihi')),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_seferler', to='api.hat')),
            ],
        ),
    ]
