# Generated by Django 5.2.9 on 2025-12-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eksefer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hatguzergah',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='durak',
            name='boylam',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='durak',
            name='enlem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hat',
            name='alt_hat_no',
            field=models.CharField(max_length=10, verbose_name='Alt Hat No'),
        ),
        migrations.AlterField(
            model_name='hat',
            name='ana_hat_no',
            field=models.CharField(max_length=10, verbose_name='Ana Hat No'),
        ),
    ]
