# Generated by Django 5.2.9 on 2025-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksefer',
            name='arac_no',
            field=models.CharField(default='Belirsiz', max_length=20, verbose_name='Atanan Araç No'),
        ),
    ]
