# Generated by Django 5.2.9 on 2025-12-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_eksefer_arac_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=50, unique=True, verbose_name='Plaka / Araç No')),
                ('durum', models.CharField(default='BOSTA', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Otobüs',
                'verbose_name_plural': 'Otobüsler',
            },
        ),
    ]
